server:
  applicationConnectors:
    - type: http
      port: 7107
  adminConnectors:
    - type: http
      port: 17107
  requestLog:
    appenders: []
serviceName: exportafacil-valdef-backend

dataSources:   
  # ===================================================================
  # Datasources Oracle
  # ===================================================================
  - uniqueResourceName: bdsigad
    jndiName: jdbc/bdsigad
    url: jdbc:oracle:thin:USAMTODO/lomaximo@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=172.18.1.18)(PORT=1552))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=prpp11g.sunat.gob.pe)))
    driverClassName: oracle.jdbc.OracleDriver
    minPoolSize: 0
    maxPoolSize: 100
    maxIdleTime: 60
    borrowConnectionTimeout: 60
    maintenanceInterval: 120
    timeoutHealthCheckInMilliseconds: 10000
    testQuery: "SELECT 1 FROM dual"
    healthCheck: true
        
logging:
  level: INFO
  loggers:
    io.dropwizard: INFO
    org.eclipse: INFO
    org.hibernate: INFO
    org.apache.camel: INFO
    com.mchange: INFO
    com.netflix: INFO
    org.jboss.weld.Version: INFO
    org.jboss.weld: INFO
    io.dropwizard.jersey.DropwizardResourceConfig: INFO
    io.dropwizard.server.ServerFactory: INFO
    org.glassfish.jersey.server.ServerRuntime: FATAL
    org.jboss.weld.environment.servlet.logging: INFO
    com.atomikos.jdbc.AtomikosConnectionProxy: ERROR
    com.circulosiete.metrics.health.hystrix: INFO
    pe.gob.sunat.controladuaneroms.exportafacil.valdef.archivo: INFO
  appenders:
    - type: file
      currentLogFilename: /logs//apps//controladuaneroms-exportafacil-valdef-backend//controladuaneroms-exportafacil-valdef-backend.log
      archivedLogFilenamePattern: /logs//apps//controladuaneroms-exportafacil-valdef-backend//controladuaneroms-exportafacil-valdef-backend-%d.log.gz
      archivedFileCount: 5
      timeZone: GMT-05:00
    - type: console
      timeZone: EST
      
# ===================================================================
# rutas
# ===================================================================
urlConsultaDeclaracion : "http://api.sunat.peru/v1/despaduanero/exportafacil/e/acta/"