apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
   name: exportafacil-valdef-backend
spec:
   maxReplicas: 3
   minReplicas: 1
   targetCPUUtilizationPercentage: 80
   scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: exportafacil-valdef-backend