apiVersion: v1
kind: Secret
metadata:
   name: exportafacil-valdef-secrets
   namespace: default
data:
   URL_CNX_ORACLE_BDSIGAD: amRiYzpvcmFjbGU6dGhpbjpVU0FNVE9ETy9sb21heGltb0AxNzIuMTguMS4xODoxNTUyOnBycHAxMWcK