apiVersion: v1
kind: ConfigMap
metadata:
  name: exportafacil-valdef-configmap
  namespace: controladuanero-exportafacil
data:
#habilitar log INFO or DEBUG
    logginglevel: INFO
    loggingloggerssunat: INFO
#Parametros del config.yaml
    configyaml:  |
         server:
           applicationConnectors:
             - type: http
               port: 7106
           adminConnectors:
             - type: http
               port: 17106
           requestLog:
             appenders: []
         serviceName: exportafacil-valdef-backend
         dataSources:
           # ===================================================================
           # Datasources Oracle
           # ===================================================================
           - uniqueResourceName: bdsigad
             jndiName: jdbc/bdsigad
             url: ${URL_CNX_ORACLE_BDSIGAD}
             driverClassName: oracle.jdbc.OracleDriver
             minPoolSize: 10
             maxPoolSize: 20
             maxIdleTime: 60
             borrowConnectionTimeout: 30
             maintenanceInterval: 360
             timeoutHealthCheckInMilliseconds: 30000
             testQuery: SELECT 1 FROM dual
             healthCheck: true
         logging:
           level: ${logginglevel}
           loggers:
             io.dropwizard: INFO
             org.eclipse: INFO
             org.hibernate: INFO
             org.apache.camel: INFO
             com.mchange: INFO
             com.netflix: INFO
             org.jboss.weld.Version: INFO
             org.jboss.weld: INFO
             io.dropwizard.jersey.DropwizardResourceConfig: INFO
             io.dropwizard.server.ServerFactory: INFO
             org.glassfish.jersey.server.ServerRuntime: FATAL
             org.jboss.weld.environment.servlet.logging: INFO
             com.atomikos.jdbc.AtomikosConnectionProxy: ERROR
             com.circulosiete.metrics.health.hystrix: INFO
             pe.gob.sunat.controladuaneroms.exportafacil.valdef: ${loggingloggerssunat}
           appenders:
             - type: file
               currentLogFilename: /logs//apps//controladuaneroms-exportafacil-valdef-backend//controladuaneroms-exportafacil-valdef-backend.log
               archivedLogFilenamePattern: /logs//apps//controladuaneroms-exportafacil-valdef-backend//controladuaneroms-exportafacil-valdef-backend-%d.log.gz
               archivedFileCount: 5
               timeZone: GMT-05:00
             - type: console
               timeZone: EST
         # ===================================================================
         # rutas
         # ===================================================================
         urlConsultaDeclaracion : http://api.sunat.peru/v1/despaduanero/exportafacil/e/acta/